config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'home/about' => 'homes#about',as: 'about'
  devise_for :users
  get '/search' => 'searchs#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
  end

  get ':id/followings' => 'users#followings', as: 'followings'
  get ':id/followers' => 'users#followers', as: 'followers'
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence:true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: {scope: :book_id}

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, uniqueness: {scope: :followed_id}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :my_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :my_relationships, source: :followed

  has_many :you_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :you_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}
  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    my_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    my_relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(comment_params)
    @comment.book_id = @book.id
    @comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find(params[:id]).destroy
  end

  private

  def comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :authenticate_user!
  
  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path

  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    @book = Book.find(params[:id])
    @user = @book.user
    unless @user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy

  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    @user = User.find(params[:user_id])
    @relationship = Relationship.find_by(followed_id: @user.id, follower_id: current_user.id)
    @relationship.destroy
    redirect_to request.referer
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    if params[:model] == "Book" 
      if params[:match] == "0"
        @search = Book.where("title = :query OR body = :query", query: params[:query])
      elsif params[:match] == "1"
        @search = Book.where("title LIKE :query OR body LIKE :query", query: "%#{params[:query]}%")
      end
    elsif params[:model] == "User" 
      if params[:match] == "0"
        query = p(params[:query]) 
        @search = User.where("name = :query OR introduction = :query", query: params[:query])
      elsif params[:match] == "1"
        @search = User.where("name LIKE :query OR introduction LIKE :query", query: "%#{params[:query]}%")
      end
    end
    @model = params[:model]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @relationship = Relationship.find_by(follower_id: current_user.id, followed_id: @user.id)
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit

  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
<%= form_with model: [book, comment], method: :post, local: false do |f| %>
  <%= f.text_area :comment, class:"comment-create" %>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/_count.html.erb
コメント数:<%= book.book_comments.count %>

app/views/book_comments/_each.html.erb
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td style="display: flex; align-items: center; gap: 10px;">
      <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
      <%= book_comment.user.name %>
    </td>
    <td>
      <%= book_comment.comment %> 
    </td>
    <% if book_comment.user == current_user %>
      <td>
        <%= link_to 'Destroy', book_book_comment_path(@book, book_comment), method: :delete, remote: true, class: "comment-destroy" %>
      </td>
    <% end %>
  </tr>
<% end %>

app/views/book_comments/create.js.erb
$("#book-comments-count").html("<%= j(render 'book_comments/count', book: @book) %>");
$("#comment-index").html("<%= j(render 'book_comments/each', book: @book) %>");
$(".comment-create").val("");

app/views/book_comments/destroy.js.erb
if ($("#book-comments-count").length) {
  $("#book-comments-count").html("<%= j(render 'book_comments/count', book: @book) %>");
}
if ($("#comment-index").length) {
  $("#comment-index").html("<%= j(render 'book_comments/each', book: @book) %>");
}

app/views/books/_form.html.erb
<%= form_with model:book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to(book.user) do %>
            <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td class="<%= book.id %>" >
            <%= render 'favorites/favorite-btn', book: book %>
        </td>
        <td>
          コメント数:<%= book.book_comments.count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
			<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'layouts/errors', obj: @book %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td>
            <%= link_to(@book.user) do %>
              <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to @book.title, @book %>
          </td>
          <td>
            <%= @book.body %>
          </td>
          <td class="<%= @book.id %>" >
            <%= render 'favorites/favorite-btn', book: @book %>
          </td>          
          <td id="book-comments-count">
            <%= render 'book_comments/count', book: @book %>
          </td>
          <% if @user  == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
      <table id="comment-index">
        <%= render 'book_comments/each', book: @book %>
      </table>
      <%= render 'book_comments/comment', book: @book, comment: @comment %>
    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book.id), method: :delete, remote: true do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
if ($(".<%= @book.id %>").length > 0) {
  $(".<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");
} else {
  console.error("エラー: .<%= @book.id %> が見つかりませんでした");
}

app/views/favorites/destroy.js.erb
if ($(".<%= @book.id %>").length > 0) {
  $(".<%= @book.id %>").html("<%= j( render 'book_comments/each', book: @book ) %>");
} else {
  console.error("エラー: .<%= @book.id %> が見つかりませんでした");
}

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/searchs/search.html.erb
<h1>Books search </h1>
<table>
  <% if @model == "Book" %>
    <tr>
      <th><th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
    <% @search.each do |book| %>
      <tr>
        <td>
          <%= image_tag book.user.get_profile_image, size: '50x50' %>
        </td>
        <td>
          <%= book.title %>
        </td>
        <td>
          <%= book.body %>
        </td>   
      </tr>
    <% end %>
  <% elsif @model == "User" %>
    <tr>
      <th><th>
      <th>Name</th>
      <th>Introduction</th>
    </tr>
    <% @search.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.get_profile_image, size: '50x50' %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <%= user.introduction %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td>
          <% relationship = Relationship.find_by(followed_id: user.id, follower_id: current_user.id) %>
          <% if current_user.following?(user) %>
            <%= link_to "フォローを外す", user_relationship_path(current_user.id, relationship.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-md-3">
      <table class='table'>
        <tr>
          <%= image_tag user.get_profile_image, size:'100x100' %></tr>
        <tr>
	        <th>name</th>
	        <th><%= user.name %></th>
        </tr>
        <tr>
	        <th>introduction</th>
	        <th><%= user.introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= link_to user.followings.count, followings_path(user.id) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to user.followers.count, followers_path(user.id) %></th>
        </tr>
      </table>

      <% if current_user.id == user.id %>
        <div class='row'>
          <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
      <% else %>
        <% relationship = Relationship.find_by(followed_id: user.id, follower_id: current_user.id) %>
        <% if current_user.following?(user) %>
          <%= link_to "フォローを外す", user_relationship_path(user.id, relationship.id), method: :delete %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
        <% end %>
      <% end %>

    

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
<%= render 'index', users: @users %>

app/views/users/followings.html.erb
<h1>Follower Users</h1>
<%= render 'index', users: @users %>

app/views/users/index.html.erb
<h2>User info</h2>
<%= render 'info', user: current_user %>

<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book, relationship: @relationship %>
</div>

<div class = "col-md-8 offset-md-1">
  <h2>Users</h2>
  <%= render 'index',users: @users %>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>